"""empty message

Revision ID: 939813ec314a
Revises: 0eed45dd8a4d
Create Date: 2023-01-14 18:48:05.738693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939813ec314a'
down_revision = '0eed45dd8a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('info', sa.String(length=256), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
