"""empty message

Revision ID: a04d228072a0
Revises: 1009e911c963
Create Date: 2023-01-13 23:05:07.570942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a04d228072a0'
down_revision = '1009e911c963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
